---
abstract: 'Use the TropoAPI via Perl'
author:
  - 'Renee Baecker <module@renee-baecker.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tropo
requires:
  Class::Method::Modifiers: 0
  HTTP::Tiny: 0
  IO::Socket::SSL: 1.56
  JSON: 2.53
  Moo: 0
  Net::SSLeay: 1.49
  Path::Tiny: 0
  Type::Tiny: 0.008
  URI::Escape: 0
  XML::Simple: 0
version: 0.03
